Repository SWUNITZEL/fiterview_backend, pull requests merged in 2025-05, with the labels that each got.

#31 Feat: 머리, 어깨 움직임 측정 및 자세분석
  app/analysis/hand.py
  app/analysis/human_posture_analysis_video.py
  app/analysis/postureAnalysis.py
  app/repository/posture_repository.py
Labels: ✨ Feature

#35 [FEAT] 표정 분석 함수 추가
  app/analysis/facial_analysis.py
Labels: ✨ Feature

#38 [FIX] 표정분석 threshold 수정
  app/analysis/facial_analysis.py
Labels: 🐞 Fix

#42 [FIX] 영상 업로드 API 경로 및 request 수정
  Dockerfile
  app/routers/upload_router.py
Labels: 🐞 Fix

#45 [FIX] ws 경로 수정 및 오디오 데이터 tempfile로 저장
  app/main.py
  app/websocket/stt_handler.py
Labels: 🐞 Fix

#47 [FEAT] 응답 통일 및 에러 핸들러 추가
  app/core/exceptions/__init__.py
  app/core/exceptions/base.py
  app/core/exceptions/custom.py
  app/core/exceptions/handlers.py
  app/core/response.py
  app/main.py
Labels: ✨ Feature

#50 [FEAT] 면접 대기실, 얼굴 랜드 마크 기준점 계산
  app/analysis/gazeAnalysis.py
  app/core/response.py
  app/main.py
  app/models/interview/interview_waiting_room.py
  app/repository/interview_repository.py
  app/routers/interview_router.py
  app/routers/upload_router.py
  app/services/interview_service.py
  app/services/land_mark_service.py
  app/websocket/stt_handler.py
Labels: ✨ Feature

#52 [FEAT model 정의
  app/models/answer_model.py
  app/models/combine_model.py
  app/models/interview_model.py
  app/models/question_model.py
  app/models/user_model.py
  app/repository/interview_repository.py
  app/repository/user_repository.py
  app/routers/interview_router.py
  app/routers/user_router.py
  app/schemas/response/__init__.py
  app/schemas/response/interview_waiting_room_response.py
  app/services/interview_service.py
  app/websocket/clova_speech_streaming.py
Labels: ✨ Feature, ♻️ Refactor

#55 [FIX] dockerfile cv2 설치 추가
  Dockerfile
Labels: ✨ Feature

#56 [FIX] dockerfile 에러 수정
  Dockerfile
Labels: 🌎 Deploy, 🐞 Fix

#61 [FEAT]: 영상 s3에 업로드 및 답변 분석 연결
  app/core/config.py
  app/main.py
  app/models/answer_model.py
  app/repository/answer_repository.py
  app/routers/answer_router.py
  app/routers/document_router.py
  app/routers/interview_router.py
  app/services/answer_service.py
  app/services/interview_service.py
  app/services/stt_service.py
  app/services/video_service.py
  app/websocket/interview_websocket.py
  requirements.txt
Labels: ✨ Feature

#63 [REFACTOR] snake_case로 통일
  app/models/combine_model.py
  app/models/interview_model.py
  app/models/question_model.py
  app/schemas/response/interview_waiting_room_response.py
  app/services/interview_service.py
Labels: ♻️ Refactor

#65 [FEAT] 면접 조합 생성 API(면접 시작하기) 추가
  app/models/combine_model.py
  app/repository/combine_repository.py
  app/routers/interview_router.py
  app/schemas/request/create_combine_request.py
  app/schemas/response/create_combine_response.py
  app/services/combine_service.py
  app/services/interview_service.py
Labels: ✨ Feature

#70 [FEAT] 페르소나별 질문생성 API 추가
  app/repository/persona_repository.py
  app/routers/persona_question_router.py
  app/services/pdf_service.py
  app/services/persona_question_service.py
Labels: ✨ Feature

#87 [FIX] AWS_REGION 추가
  app/core/config.py
Labels: 🐞 Fix

#96 [REFACTOR] s3 업로드 관련 코드 리팩토링
  app/aws.py
  app/routers/persona_question_router.py
  app/services/pdf_service.py
  app/services/s3_service.py
  app/services/video_service.py
  app/websocket/interview_websocket.py
Labels: ♻️ Refactor

#103 [FEAT] 영상 분석 API
  app/analysis/face_mesh_analysis.py
  app/analysis/facial_analysis.py
  app/analysis/gazeAnalysis.py
  app/analysis/postureAnalysis.py
  app/core/exceptions/custom.py
  app/models/answer_model.py
  app/models/interview_model.py
  app/repository/interview_repository.py
  app/routers/interview_router.py
  app/schemas/response/analysis_video_response.py
  app/schemas/response/create_combine_response.py
  app/schemas/response/interview_waiting_room_response.py
  app/services/answer_service.py
  app/services/interview_service.py
  app/services/land_mark_service.py
Labels: ✨ Feature

#110 [FEAT] 웹소켓 연결 후 인터뷰 진행
  app/models/question_model.py
  app/repository/question_repository.py
  app/schemas/response/interview_question_response.py
  app/services/stt_service.py
  app/websocket/interview_websocket.py
Labels: ✨ Feature

#112 [FIX] CreateCombineResponse 생성 코드 수정
  app/services/combine_service.py
  app/websocket/interview_websocket.py
Labels: 🐞 Fix
