Repository SWUNITZEL/fiterview_backend, pull requests merged in 2025-06, with the labels that each got.

#124 [FEAT] 영상 분석 결과 저장
  app/core/exceptions/custom.py
  app/models/answer_model.py
  app/repository/answer_repository.py
  app/repository/question_repository.py
  app/services/answer_service.py
  app/services/s3_service.py
Labels: ✨ Feature

#126 [Fix] question API 수정
  app/main.py
  app/models/question_model.py
  app/repository/question_repository.py
  app/routers/persona_question_router.py
  app/schemas/response/question_response.py
  app/services/persona_question_service.py
Labels: 🐞 Fix

#128 [Feat] report API 추가
  app/core/database.py
  app/main.py
  app/routers/report_router.py
  app/schemas/request/report_request.py
  app/schemas/response/report_response.py
  app/services/report_service.py
Labels: ✨ Feature

#130 [REFACTOR] 결과보고서 단건조회 수정
  app/routers/report_router.py
  app/schemas/request/report_request.py
  app/schemas/response/report_response.py
  app/services/report_service.py
Labels: ♻️ Refactor

#136 [FEAT] 답변 속도, 평균 데시벨 계산 후 저장
  app/models/answer_model.py
  app/services/stt_service.py
  app/websocket/interview_websocket.py
  requirements.txt
Labels: ✨ Feature

#138 [FIX] 영상 분석 API 버그
  app/repository/question_repository.py
Labels: 🐞 Fix

#140 [FEAT] 답변기반 꼬리질문 API 추가
  app/routers/interview_router.py
  app/schemas/response/followup_question_response.py
  app/services/followup_question_service.py
  app/services/persona_question_service.py
Labels: ✨ Feature

#146 [FIX] 질문 생성 버그 수정
  app/models/question_model.py
  app/repository/combine_repository.py
  app/repository/interview_repository.py
  app/repository/question_repository.py
  app/routers/persona_question_router.py
  app/schemas/response/question_response.py
  app/services/persona_question_service.py
Labels: 🐞 Fix

#149 [FIX] 질문 저장시 인터뷰 아이디, 질문 인덱스 저장
  app/repository/question_repository.py
  app/services/persona_question_service.py
Labels: 🐞 Fix

#151 [FEAT] 눈 깜빡임 수 측정 추가
  app/schemas/response/analysis_video_response.py
  app/services/answer_service.py
  app/websocket/interview_websocket.py
Labels: ✨ Feature

#152 [FIX] 분당 눈 깜빡임 측정으로 수정
  app/schemas/response/analysis_video_response.py
  app/services/answer_service.py
Labels: 🐞 Fix

#160 [CHORE] 질문개수 수정
  app/services/persona_question_service.py
Labels: ⚙️ Chore

#163 [REFACTOR] 질문생성 예외처리 추가
  app/services/persona_question_service.py
Labels: ♻️ Refactor

#164 [FEAT] video url 반환
  app/services/report_service.py
Labels: ✨ Feature
