Repository SWUNITZEL/fiterview_backend, pull requests merged in 2025-07, with the labels that each got.

#168 [FEAT] 텍스트 추출 안 될때 예외처리 추가
  app/websocket/interview_websocket.py
Labels: ✨ Feature

#173 [FIX] 시선 좌표 저장시 필드명 추가
  app/models/answer_model.py
  app/services/answer_service.py
Labels: 🐞 Fix

#175 [REFACTOR] 답변총평 프롬프트 개선
  app/schemas/response/report_response.py
  app/services/report_service.py
Labels: ♻️ Refactor

#177 [CHORE] 응답값 변수 추가
  app/schemas/response/report_response.py
  app/services/report_service.py
Labels: ⚙️ Chore

#178 [CHORE] 변수명 통일
  app/services/report_service.py
Labels: ⚙️ Chore

#180 [CHORE] 변수 추가
  app/services/report_service.py
Labels: ⚙️ Chore

#181 [CHORE] 예외처리 추가
  app/services/report_service.py
Labels: ⚙️ Chore

#183 [CHORE] video url 예외처리
  app/services/report_service.py
Labels: ⚙️ Chore

#184 [CHORE] existing videos 추가
  app/services/report_service.py
Labels: ⚙️ Chore

#185 [FEAT] presigned URL 변환 추가
  app/common/s3_utils.py
  app/schemas/response/report_response.py
  app/services/report_service.py
Labels: ✨ Feature
